name: Challenges
version: '${project.version}'
main: de.seniorenheim.challenges.Main
api-version: '1.20'
commands:
  challenge:
    aliases:
      - ch
  join:
    aliases:
      - chjoin
  start:
    aliases:
      - chstart
  pause:
    aliases:
      - chpause
  resume:
    aliases:
      - chresume
  reset:
    aliases:
      - chreset
  stop:
    aliases:
      - chstop